# Generated by Django 5.0.6 on 2024-06-15 20:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_reciclaje',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('rut_recolector', models.CharField(max_length=10, null=True)),
                ('cantidad_plastico', models.IntegerField(default=0)),
                ('cantidad_vidrio', models.IntegerField(default=0)),
                ('cantidad_carton', models.IntegerField(default=0)),
                ('cantidad_aluminio', models.IntegerField(default=0)),
                ('cantidad_metal', models.IntegerField(default=0)),
                ('cantidad_electrodomesticos', models.IntegerField(default=0)),
                ('latitud_posicion_ciudadano', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud_posicion_ciudadano', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitud_posicion_recolector', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud_posicion_recolector', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion_desechos_reserva',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('cantidad_plastico', models.IntegerField(default=0)),
                ('cantidad_vidrio', models.IntegerField(default=0)),
                ('cantidad_carton', models.IntegerField(default=0)),
                ('cantidad_aluminio', models.IntegerField(default=0)),
                ('cantidad_metal', models.IntegerField(default=0)),
                ('cantidad_electrodomesticos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('rut_recolector', models.CharField(max_length=10, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_plastico', models.IntegerField(default=0)),
                ('cantidad_vidrio', models.IntegerField(default=0)),
                ('cantidad_carton', models.IntegerField(default=0)),
                ('cantidad_aluminio', models.IntegerField(default=0)),
                ('cantidad_metal', models.IntegerField(default=0)),
                ('cantidad_electrodomesticos', models.IntegerField(default=0)),
                ('latitud_posicion_ciudadano', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud_posicion_ciudadano', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitud_posicion_recolector', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud_posicion_recolector', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion_recolector_ciudadano',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion_estrellas_ciudadano', models.FloatField(null=True)),
                ('calificacion_estrellas_recolector', models.FloatField(null=True)),
                ('opinion_servicio_ciudadano', models.CharField(max_length=400, null=True)),
                ('opinion_servicio_recolector', models.CharField(max_length=400, null=True)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.orden_reciclaje')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion_desechos',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('cantidad_plastico', models.IntegerField(default=0)),
                ('cantidad_vidrio', models.IntegerField(default=0)),
                ('cantidad_carton', models.IntegerField(default=0)),
                ('cantidad_aluminio', models.IntegerField(default=0)),
                ('cantidad_metal', models.IntegerField(default=0)),
                ('cantidad_electrodomesticos', models.IntegerField(default=0)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.orden_reciclaje')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('telefono_reciclador', models.IntegerField(default=0)),
                ('total_material_reciclado', models.IntegerField(default=0)),
                ('monto_pago', models.IntegerField(default=0)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.recepcion_desechos')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_pago_reserva',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('telefono_reciclador', models.IntegerField(default=0)),
                ('total_material_reciclado', models.IntegerField(default=0)),
                ('monto_pago', models.IntegerField(default=0)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.recepcion_desechos_reserva')),
            ],
        ),
        migrations.AddField(
            model_name='recepcion_desechos_reserva',
            name='id_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.reserva_orden'),
        ),
        migrations.CreateModel(
            name='Calificacion_recolector_ciudadano_reserva',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion_estrellas_ciudadano', models.FloatField(null=True)),
                ('calificacion_estrellas_recolector', models.FloatField(null=True)),
                ('opinion_servicio_ciudadano', models.CharField(max_length=400, null=True)),
                ('opinion_servicio_recolector', models.CharField(max_length=400, null=True)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.reserva_orden')),
            ],
        ),
        migrations.CreateModel(
            name='UserModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(blank=True, max_length=10, null=True)),
                ('dv', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('comuna', models.CharField(blank=True, max_length=80, null=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('licencia_automotriz', models.ImageField(blank=True, null=True, upload_to='licencias/')),
                ('segundo_nombre_madre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_usuario', models.CharField(choices=[('Recolector', 'Recolector'), ('Reciclador', 'Reciclador'), ('Ciudadano', 'Ciudadano'), ('Operario municipalidad', 'Operario municipalidad')], max_length=200, null=True)),
                ('new_password1', models.CharField(max_length=50, null=True)),
                ('new_password2', models.CharField(max_length=50, null=True)),
                ('validacion_recolector', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='usuarios', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='reserva_orden',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden_reciclaje',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
