# Generated by Django 5.0.4 on 2024-05-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelo',
            name='dv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
