# Generated by Django 4.2.1 on 2023-06-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_reciclaje',
            name='latitud_posicion_recolector',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orden_reciclaje',
            name='longitud_posicion_recolector',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
