# Generated by Django 4.2.1 on 2024-04-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_calificacion_recolector_ciudadano_reserva_p_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='p',
        ),
    ]
