# Generated by Django 4.2.1 on 2023-06-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_alter_orden_reciclaje_latitud_posicion_ciudadano_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion_recolector_ciudadano',
            old_name='id_calificacion',
            new_name='id',
        ),
    ]
