# Generated by Django 4.2.1 on 2024-05-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_delete_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepcion_desechos_reserva',
            old_name='id_registro_reserva',
            new_name='id_registro',
        ),
    ]
