# Generated by Django 5.0.4 on 2024-06-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_alter_usermodelo_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodelo',
            name='new_password1',
        ),
        migrations.RemoveField(
            model_name='usermodelo',
            name='new_password2',
        ),
    ]
