# Generated by Django 4.2.1 on 2023-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_rename_id_calificacion_calificacion_recolector_ciudadano_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_reciclaje',
            name='estado',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva_orden',
            name='estado',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
