# Generated by Django 4.2.1 on 2024-05-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_rename_id_registro_reserva_recepcion_desechos_reserva_id_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_pago_reserva',
            old_name='id_registro_reserva',
            new_name='id_registro',
        ),
    ]
