# Generated by Django 4.2.1 on 2023-06-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_orden_reciclaje_estado_reserva_orden_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion_recolector_ciudadano',
            old_name='id',
            new_name='id_calificacion',
        ),
    ]
