# Generated by Django 4.2.1 on 2024-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_rename_id_registro_reserva_registro_pago_reserva_id_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_reciclaje',
            name='rut_recolector',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva_orden',
            name='rut_recolector',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
