# Generated by Django 4.2.1 on 2024-05-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_orden_reciclaje_rut_recolector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_pago',
            name='telefono_reciclador',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro_pago_reserva',
            name='telefono_reciclador',
            field=models.IntegerField(default=0),
        ),
    ]
