# Generated by Django 4.2.1 on 2023-06-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_rename_id_calificacion_recolector_ciudadano_id_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion_recolector_ciudadano',
            name='calificacion_estrellas_ciudadano',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calificacion_recolector_ciudadano',
            name='calificacion_estrellas_recolector',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calificacion_recolector_ciudadano',
            name='opinion_servicio_ciudadano',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion_recolector_ciudadano',
            name='opinion_servicio_recolector',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
