# Generated by Django 4.2.1 on 2023-07-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_alter_calificacion_recolector_ciudadano_calificacion_estrellas_ciudadano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_reciclaje',
            name='latitud_posicion_ciudadano',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orden_reciclaje',
            name='latitud_posicion_recolector',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orden_reciclaje',
            name='longitud_posicion_ciudadano',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orden_reciclaje',
            name='longitud_posicion_recolector',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='reserva_orden',
            name='latitud_posicion_ciudadano',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='reserva_orden',
            name='latitud_posicion_recolector',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='reserva_orden',
            name='longitud_posicion_ciudadano',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='reserva_orden',
            name='longitud_posicion_recolector',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
