# Generated by Django 4.2.1 on 2023-08-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_alter_orden_reciclaje_latitud_posicion_ciudadano_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden_reciclaje',
            old_name='cantidad_material',
            new_name='aluminio',
        ),
        migrations.RenameField(
            model_name='registro_entrega_material',
            old_name='cantidad_material',
            new_name='aluminio',
        ),
        migrations.RenameField(
            model_name='reserva_orden',
            old_name='cantidad_material',
            new_name='aluminio',
        ),
        migrations.RemoveField(
            model_name='orden_reciclaje',
            name='tipo_material',
        ),
        migrations.RemoveField(
            model_name='registro_entrega_material',
            name='tipo_material',
        ),
        migrations.RemoveField(
            model_name='reserva_orden',
            name='tipo_material',
        ),
        migrations.AddField(
            model_name='orden_reciclaje',
            name='carton',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden_reciclaje',
            name='plastico',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden_reciclaje',
            name='vidrio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_entrega_material',
            name='carton',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_entrega_material',
            name='plastico',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_entrega_material',
            name='vidrio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva_orden',
            name='carton',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva_orden',
            name='plastico',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva_orden',
            name='vidrio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
