# Generated by Django 4.2.1 on 2023-08-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0010_alter_orden_reciclaje_aluminio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden_reciclaje',
            old_name='aluminio',
            new_name='cantidad_aluminio',
        ),
        migrations.RenameField(
            model_name='orden_reciclaje',
            old_name='carton',
            new_name='cantidad_carton',
        ),
        migrations.RenameField(
            model_name='orden_reciclaje',
            old_name='plastico',
            new_name='cantidad_plastico',
        ),
        migrations.RenameField(
            model_name='orden_reciclaje',
            old_name='vidrio',
            new_name='cantidad_vidrio',
        ),
        migrations.RenameField(
            model_name='registro_entrega_material',
            old_name='aluminio',
            new_name='cantidad_aluminio',
        ),
        migrations.RenameField(
            model_name='registro_entrega_material',
            old_name='carton',
            new_name='cantidad_carton',
        ),
        migrations.RenameField(
            model_name='registro_entrega_material',
            old_name='plastico',
            new_name='cantidad_plastico',
        ),
        migrations.RenameField(
            model_name='registro_entrega_material',
            old_name='vidrio',
            new_name='cantidad_vidrio',
        ),
        migrations.RenameField(
            model_name='reserva_orden',
            old_name='aluminio',
            new_name='cantidad_aluminio',
        ),
        migrations.RenameField(
            model_name='reserva_orden',
            old_name='carton',
            new_name='cantidad_carton',
        ),
        migrations.RenameField(
            model_name='reserva_orden',
            old_name='plastico',
            new_name='cantidad_plastico',
        ),
        migrations.RenameField(
            model_name='reserva_orden',
            old_name='vidrio',
            new_name='cantidad_vidrio',
        ),
    ]
