# Generated by Django 4.2.1 on 2023-08-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0011_rename_aluminio_orden_reciclaje_cantidad_aluminio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion_recolector_ciudadano_reserva',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion_estrellas_ciudadano', models.FloatField(null=True)),
                ('calificacion_estrellas_recolector', models.FloatField(null=True)),
                ('opinion_servicio_ciudadano', models.CharField(max_length=400, null=True)),
                ('opinion_servicio_recolector', models.CharField(max_length=400, null=True)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.reserva_orden')),
            ],
        ),
    ]
